is_test: false

# Data Collection
scraping:
  headhunter:
    enabled: true
    output_filename_base: "data/raw/headhunter/raw"
    start_date: null  # will default to 1 day ago, format as "YYYY-MM-DD"
    end_date: null  # will default to today, format as "YYYY-MM-DD"
    per_page: 5
    max_pages: 1

  getmatch:
    enabled: true
    output_filename_base: "data/raw/getmatch/raw"
    num_pages: 1
    output_format: "csv"

# Data Preprocessing
preprocessing:
  input_filename_base:
    getmatch: "data/raw/getmatch/raw"
    headhunter: "data/raw/headhunter/raw"
  merged_path: "data/preprocessed/merged/merged"
  output_path: "data/preprocessed/preprocessed/preprocessed.csv"
  historical_data_path: "data/preprocessed/historical/preprocessed.csv"
  drift_thresholds:
    ks_pvalue_threshold: 0.05
    js_divergence_threshold: 0.1
    psi_threshold: 0.2
  salary_outliers:
    bottom_percentile: 0.001
    top_percentile: 1.0    # Keep all high values

# Feature Engineering
features:
  preprocessed_data_base: "data/preprocessed/preprocessed/preprocessed"
  output_base: "data/processed/processed"
  target_base: "data/processed/target/target"
  target_name: "log_salary_from"
  features:
    catboost:
      text:
        - "title"
        - "location"
        - "company"
        - "description_no_numbers_with_skills"
      categorical:
        - "source"
      numeric:
        - "experience_from"
        - "experience_to_adjusted_10"
        - "description_size"
    transformer:
      text:
        - "description_no_numbers"
        - "title_company_location_skills_source"
    bi_gru_cnn:
      text:
        - "description_no_numbers"
        - "title_company_location_skills_source"

  catboost:
    features_base: "data/processed/catboost/features"
  transformer:
    features_base: "data/processed/transformer"
    tokenizer: "intfloat/multilingual-e5-small"
    tokenizer_test: "sergeyzh/rubert-tiny-turbo"
    add_query_prefix: true
    feature_processing:
      - name: "description_no_numbers"
        max_len: 512
        base: "data/processed/transformer/description_no_numbers"
      - name: "title_company_location_skills_source"
        max_len: 256
        base: "data/processed/transformer/title_company_location_skills_source"

  bi_gru_cnn:
    features_dir: "data/processed/bi_gru_cnn"

  test_size: 1 # 25% of the data will be used for testing the downstream pipeline

# Models
models:
  catboost:
    mlflow_run_name: "catboost"
    tokenizer_id: "Space"
    dictionary_id: "Word"
    max_dictionary_size: '50000'
    occurrence_lower_bound: '25'
    occurrence_lower_bound_test: '0'
    gram_order: "1"
    learning_rate: 0.05
    bagging_temperature: 0
    random_strength: 10
    l2_leaf_reg: 0
    depth: 4
    iterations: 2000
    iterations_test: 100
    early_stopping_rounds: 100
    loss_function: "RMSE"
    eval_metric: "R2"
    save_dir: "models/catboost"
    y_pred_base: "data/predictions/catboost/y_pred"
    y_true_base: "data/predictions/catboost/y_true"
    use_latest_model_flag: true

  transformer:
    enabled: false
    mlflow_run_name: "transformer"
    model_name: "intfloat/multilingual-e5-small"
    model_name_test: "sergeyzh/rubert-tiny-turbo"
    hidden_size: 384
    hidden_size_test: 312
    mlp_hidden_size: 128
    num_heads: 8
    dropout: 0.1
    batch_size: 32
    learning_rate: 2e-5
    num_epochs: 10
    num_epochs_test: 2
    weight_decay: 1e-2
    loss_function: "huber" # [mse, huber]
    save_base: "models/transformer/transformer"
    y_pred_base: "data/predictions/transformer/y_pred"
    y_true_base: "data/predictions/transformer/y_true"
    use_latest_model_flag: false

  blended:
    mlflow_run_name: "blended"
    catboost_weight: 0.5
    transformer_weight: 0.5


# Training
training:
  main_seed: 42
  seeds:
    - 42
    - 78687
    - 123123
  test_size: 0.2
  # train_size: 0.8

  metrics:
    - "mae"
    - "r2"
    - "rmse"

  confidence_interval:
    alpha: 0.05

# Experiment Tracking
logging:
  mlflow:
    tracking_uri: "http://mlflow:5000"  # Update to use service name
    experiment_name: "salary_prediction"

  save_artifacts: true
  log_predictions: true
