name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main  # Add push trigger only for main branch for deployment

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint pre-commit
      - name: Run linters
        run: |
          cd backend
          pre-commit run --all-files
          pylint --rcfile=../.pylintrc \
            --ignore=notebook \
            --disable=E0606,W0707,C0415,W0107,E1126 \
            $(git ls-files '*.py')

  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.base.blended.txt
          python -m pip install -r backend/requirements.fastapi.txt
          python -m pip install pytest pytest-cov pytest-mock httpx

      - name: Run tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          cd backend
          pytest tests/ -vvv --cov=. --cov-report term-missing -o log_cli=1

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run tests
        env:
          API_URL: "https://api.example.com"
          API_KEY: "test-api-key"
        run: |
          cd frontend
          npm test

  # This job will only run on push to main (after PR merge)
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem

          # Remove any existing known hosts for this IP
          ssh-keygen -f ~/.ssh/known_hosts -R "${{ secrets.EC2_HOST }}" || true

          cat >> ~/.ssh/config << EOF
          Host ec2
            HostName ${{ secrets.EC2_HOST }}
            User ${{ secrets.EC2_USER }}
            IdentityFile ~/.ssh/ec2_key.pem
            StrictHostKeyChecking accept-new
          EOF

      - name: Deploy to EC2
        run: |
          ssh ec2 'cd /home/${{ secrets.EC2_USER }}/tech-salary-prediction && \
                  ./scripts/pull_and_build.sh'
